spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/dragon-empire/springcloudconfig
          searchPaths: src/main/resources

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/